kind: Pod
metadata:
  name: git, maven and kaniko
spec:
  containers:
  - name: git-maven
    image: alecharp/maven-build-tools:a43bb39
    command:
    - cat
    tty: true
    volumeMounts:
      - mountPath: /root/.m2/repository
        name: maven-pv-storage
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: supportbeescloud # existing kubernetes secret for login into the Docker Registry
          items:
            - key: .dockerconfigjson
              path: config.json
  - name: maven-pv-storage 
    persistentVolumeClaim:
      claimName: maven-pv-claim # this pvc (maven_cache_pvc.yaml) needs to be created before running the agent
      readOnly: false